package io.moov.watchman.api.dto;

import io.moov.watchman.config.WeightConfig;

/**
 * DTO for WeightConfig - 54 parameters across all migration phases.
 */
public record WeightConfigDTO(
    // Original 13
    double nameWeight,
    double addressWeight,
    double criticalIdWeight,
    double supportingInfoWeight,
    double minimumScore,
    double exactMatchThreshold,
    boolean nameComparisonEnabled,
    boolean altNameComparisonEnabled,
    boolean addressComparisonEnabled,
    boolean govIdComparisonEnabled,
    boolean cryptoComparisonEnabled,
    boolean contactComparisonEnabled,
    boolean dateComparisonEnabled,
    // BSA compliance thresholds Phase 1 (7)
    double aliasTieBreakerThreshold,
    double exactMatchCriticalIdThreshold,
    double exactMatchIdWeight,
    double exactMatchNameWeight,
    double aliasScoreMultiplier,
    double aliasMinimumScore,
    double aliasBoostMaxScore,
    double aliasBoostAmount,
    // Address field weights Phase 2 (7)
    double addressLine1Weight,
    double addressLine2Weight,
    double addressCityWeight,
    double addressStateWeight,
    double addressPostalWeight,
    double addressCountryWeight,
    double addressHighConfidenceThreshold,
    // Date comparison params Phase 2 (12)
    double dateYearDecayRate,
    double dateDistantYearScore,
    double dateMonthTolerance1,
    double dateMonthTolerance2,
    double dateMonthTolerance3Plus,
    double dateDayTolerance0to3Start,
    double dateDayTolerance0to3Decay,
    double dateDayTolerance4to7,
    double dateDayTolerance8Plus,
    double dateYearWeight,
    double dateMonthWeight,
    double dateDayWeight,
    // SupportingInfo / Title thresholds Phase 3 (5)
    double supportingInfoMatchedThreshold,
    double supportingInfoExactThreshold,
    double supportingInfoSecondaryPenalty,
    double titleMatchedThreshold,
    double titleExactThreshold,
    // Affiliation / Name thresholds Phase 4 (4)
    double affiliationNameThreshold,
    double affiliationExactThreshold,
    double affiliationTypeScoreThreshold,
    double nameEarlyExitThreshold,
    // Scorer address weights Phase 5 (3)
    double scorerAddressCountryWeight,
    double scorerAddressCityWeight,
    double scorerAddressLineWeight,
    // Alias selection Phase 6 (2)
    double aliasSelectionTolerance,
    double aliasCoverageMinScore
) {
    public static WeightConfigDTO from(WeightConfig config) {
        return new WeightConfigDTO(
            config.getNameWeight(),
            config.getAddressWeight(),
            config.getCriticalIdWeight(),
            config.getSupportingInfoWeight(),
            config.getMinimumScore(),
            config.getExactMatchThreshold(),
            config.isNameComparisonEnabled(),
            config.isAltNameComparisonEnabled(),
            config.isAddressComparisonEnabled(),
            config.isGovIdComparisonEnabled(),
            config.isCryptoComparisonEnabled(),
            config.isContactComparisonEnabled(),
            config.isDateComparisonEnabled(),
            config.getAliasTieBreakerThreshold(),
            config.getExactMatchCriticalIdThreshold(),
            config.getExactMatchIdWeight(),
            config.getExactMatchNameWeight(),
            config.getAliasScoreMultiplier(),
            config.getAliasMinimumScore(),
            config.getAliasBoostMaxScore(),
            config.getAliasBoostAmount(),
            config.getAddressLine1Weight(),
            config.getAddressLine2Weight(),
            config.getAddressCityWeight(),
            config.getAddressStateWeight(),
            config.getAddressPostalWeight(),
            config.getAddressCountryWeight(),
            config.getAddressHighConfidenceThreshold(),
            config.getDateYearDecayRate(),
            config.getDateDistantYearScore(),
            config.getDateMonthTolerance1(),
            config.getDateMonthTolerance2(),
            config.getDateMonthTolerance3Plus(),
            config.getDateDayTolerance0to3Start(),
            config.getDateDayTolerance0to3Decay(),
            config.getDateDayTolerance4to7(),
            config.getDateDayTolerance8Plus(),
            config.getDateYearWeight(),
            config.getDateMonthWeight(),
            config.getDateDayWeight(),
            config.getSupportingInfoMatchedThreshold(),
            config.getSupportingInfoExactThreshold(),
            config.getSupportingInfoSecondaryPenalty(),
            config.getTitleMatchedThreshold(),
            config.getTitleExactThreshold(),
            config.getAffiliationNameThreshold(),
            config.getAffiliationExactThreshold(),
            config.getAffiliationTypeScoreThreshold(),
            config.getNameEarlyExitThreshold(),
            config.getScorerAddressCountryWeight(),
            config.getScorerAddressCityWeight(),
            config.getScorerAddressLineWeight(),
            config.getAliasSelectionTolerance(),
            config.getAliasCoverageMinScore()
        );
    }
}
